name: testing
description: A new Flutter application.

publish_to: "none" # 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it:
  http:

  responsify:
  data_connection_checker:
  flutter_speed_dial: ^3.0.5
  dropdown_search:
  flutter_swiper:
  shared_preferences:

  fluttertoast:
  loader_overlay:
  filter_list: any
  font_awesome_flutter:
  # expansion_card:
  # cell_calendar:
  async:
  
  percent_indicator:
  # syncfusion_flutter_calendar:
  intl:
  date_format:
  shimmer: 
  nb_utils:
  connectivity:
  dio:
  webview_flutter:
  unicorndial:
  flutter_range_slider:
  modal_bottom_sheet:
  cached_network_image:
  lottie:
  signature:

  # snapshot_carousel: ^0.0.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  ios: true
  android: true
  image_path: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-VariableFont_wght.ttf
  #   style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
